import { NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { getProject, getProjectArtifacts } from '@/lib/supabase/queries';
import { safeFileName } from '@/lib/security';

export async function POST(request: Request) {
  const supabase = await createServerSupabaseClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json(
      { success: false, error: { message: 'Unauthorized' } },
      { status: 401 }
    );
  }

  const body = await request.json();
  const { projectId } = body;

  if (!projectId) {
    return NextResponse.json(
      { success: false, error: { message: 'Project ID is required' } },
      { status: 400 }
    );
  }

  const project = await getProject(projectId, user.id);
  if (!project) {
    return NextResponse.json(
      { success: false, error: { message: 'Project not found' } },
      { status: 404 }
    );
  }

  const artifacts = await getProjectArtifacts(projectId);
  const artifactMap = artifacts.reduce((acc, a) => {
    acc[a.type] = a.content;
    return acc;
  }, {} as Record<string, unknown>);

  const markdown = generateMarkdown(project, artifactMap);

  const fileName = safeFileName(project.name, 'md');

  return new Response(markdown, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  });
}

function generateMarkdown(project: any, artifacts: Record<string, any>): string {
  let md = `# ${project.name}\n\n`;
  md += `**Idea:** ${project.idea}\n\n`;
  md += `**Problem:** ${project.problem_description || 'Not specified'}\n\n`;
  md += `---\n\n`;

  const analysis = artifacts['startup_analysis'];
  if (analysis) {
    md += `## Startup Analysis\n\n`;
    md += `### Problem Statement\n${analysis.problemStatement || ''}\n\n`;
    md += `### Target Audience\n${analysis.targetAudience || ''}\n\n`;
    md += `### Value Proposition\n${analysis.valueProposition || ''}\n\n`;
    md += `### Market Opportunity\n${analysis.marketOpportunity || ''}\n\n`;
    if (analysis.risks?.length) {
      md += `### Risks\n${analysis.risks.map((r: string) => `- ${r}`).join('\n')}\n\n`;
    }
    if (analysis.recommendations?.length) {
      md += `### Recommendations\n${analysis.recommendations.map((r: string) => `- ${r}`).join('\n')}\n\n`;
    }
  }

  const personas = artifacts['personas'];
  if (personas?.personas?.length) {
    md += `## User Personas\n\n`;
    for (const p of personas.personas) {
      md += `### ${p.name} — ${p.role}\n\n`;
      if (p.goals?.length) md += `**Goals:**\n${p.goals.map((g: string) => `- ${g}`).join('\n')}\n\n`;
      if (p.painPoints?.length) md += `**Pain Points:**\n${p.painPoints.map((pp: string) => `- ${pp}`).join('\n')}\n\n`;
      if (p.motivations?.length) md += `**Motivations:**\n${p.motivations.map((m: string) => `- ${m}`).join('\n')}\n\n`;
    }
  }

  const mvp = artifacts['mvp_scope'];
  if (mvp) {
    md += `## MVP Scope\n\n`;
    if (mvp.mustHave?.length) md += `### Must Have\n${mvp.mustHave.map((f: string) => `- ${f}`).join('\n')}\n\n`;
    if (mvp.shouldHave?.length) md += `### Should Have\n${mvp.shouldHave.map((f: string) => `- ${f}`).join('\n')}\n\n`;
    if (mvp.couldHave?.length) md += `### Could Have\n${mvp.couldHave.map((f: string) => `- ${f}`).join('\n')}\n\n`;
    if (mvp.excludedFeatures?.length) md += `### Won't Have (v1)\n${mvp.excludedFeatures.map((f: string) => `- ${f}`).join('\n')}\n\n`;
  }

  const roadmap = artifacts['roadmap'];
  if (roadmap) {
    md += `## Product Roadmap\n\n`;
    if (roadmap.phase1?.length) md += `### Phase 1: Core MVP\n${roadmap.phase1.map((i: string) => `- ${i}`).join('\n')}\n\n`;
    if (roadmap.phase2?.length) md += `### Phase 2: Validation\n${roadmap.phase2.map((i: string) => `- ${i}`).join('\n')}\n\n`;
    if (roadmap.phase3?.length) md += `### Phase 3: Growth\n${roadmap.phase3.map((i: string) => `- ${i}`).join('\n')}\n\n`;
  }

  const health = artifacts['health_score'];
  if (health) {
    md += `## Health Score\n\n`;
    md += `**Score:** ${health.score}/100\n\n`;
    if (health.strengths?.length) md += `**Strengths:**\n${health.strengths.map((s: string) => `- ${s}`).join('\n')}\n\n`;
    if (health.risks?.length) md += `**Risks:**\n${health.risks.map((r: string) => `- ${r}`).join('\n')}\n\n`;
    if (health.recommendations?.length) md += `**Recommendations:**\n${health.recommendations.map((r: string) => `- ${r}`).join('\n')}\n\n`;
  }

  md += `---\n*Generated by Origina*\n`;
  return md;
}
